<?php
/**
 * Created by PhpStorm.
 * User: koupzy
 * Date: 10/02/19
 * Time: 13:00
 */

namespace AppBundle\Form;


use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class precActivityType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('periode_de', DateTimeType::class)
            ->add('periode_a', DateTimeType::class)
            ->add('prec_rccm', TextType::class)
            ->add('activite', TextType::class)
            ->add('princip_etab', TextType::class)
            ->add('second_etab', TextType::class)
            ->add('rccm', TextType::class);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        parent::configureOptions($resolver); // TODO: Change the autogenerated stub
    }


}